name: Flutter CI

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '2.10.4'

      - run: flutter pub get

      - run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - run: flutter format --set-exit-if-changed .

      - run: flutter analyze .
